language: php

php:
  - 5.4
  - 5.5

install:
  - composer self-update && composer --version
  - composer install

script:
  # @TODO Bugfix chmod of logs directory.
  - chmod 0777 -R ./tests/_log
  - chmod 0777 -R ./tests/_runtime
  - make test

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./tests/_log/coverage.xml